### ISSUE TITLE
Reddit CSS minor fix

### ISSUE THREAD

**Issue by ave-satanas** [phallus/dotfiles#2]
Add 
```
.redesign-beta-optin {
    display: none !important;
}
```
in order to disable the "visit new reddit" banner and restore functionality to your subreddits menu. 

![image](https://user-images.githubusercontent.com/40011472/41796288-be4d8274-761a-11e8-9bc6-38b2274b0315.png)

**Comment by phallus** [comment]
[Functional on my end with no change.](https://u.teknik.io/iSOCS.png) Regardless, .redesign-beta-optin has been hidden to prevent any future problems for others.
